"use client";

import React, { useState } from "react";
import { ParallelApiItem } from "@/types/portal";
import {
  MapPin,
  Radio,
  ArrowRight,
  CheckCircle2,
  Lock,
  Cpu,
  Layers,
  Sparkles,
  Volume2,
  FileCode,
  ShieldCheck,
  Terminal,
  Activity,
  Compass,
  ArrowDown,
} from "lucide-react";

interface AgriArchitectureVisualizerProps {
  parallelApis?: ParallelApiItem[];
}

export const AgriArchitectureVisualizer: React.FC<AgriArchitectureVisualizerProps> = ({
  parallelApis = [],
}) => {
  const [selectedParcel, setSelectedParcel] = useState({
    id: "MH-PUN-402 (7/12 Satbara: 882)",
    location: "Haveli, Pune, Maharashtra",
    coordinates: "18.5204° N, 73.8567° E",
    soil: "Black Cotton Soil (Vertisol)",
    crop: "Sugarcane (Adsali) · 2.5 Acres",
  });

  const [activeApi, setActiveApi] = useState<number>(0);
  const [activeCodeTab, setActiveCodeTab] = useState<"nutrient" | "profit" | "labor">("nutrient");

  const parcels = [
    {
      id: "MH-PUN-402 (7/12 Satbara: 882)",
      location: "Haveli, Pune, Maharashtra",
      coordinates: "18.5204° N, 73.8567° E",
      soil: "Black Cotton Soil (Vertisol)",
      crop: "Sugarcane (Adsali) · 2.5 Acres",
    },
    {
      id: "MH-BAR-108 (7/12 Satbara: 314)",
      location: "Baramati, Pune, Maharashtra",
      coordinates: "18.1517° N, 74.5772° E",
      soil: "Medium Deep Black Soil",
      crop: "Sugarcane (Pre-seasonal) · 3.0 Acres",
    },
  ];

  const typescriptMathCode = {
    nutrient: `// -------------------------------------------------------------
// DETERMINISTIC RULE ENGINE: ICAR PACKAGE OF PRACTICES (TypeScript)
// Dosages are computed by a rule engine, never generated by the LLM
// -------------------------------------------------------------
import { ICAR_POP_REGISTRY, FertilizationInput, FertilizationResult } from "@/lib/icar-fertilizer";

export function calculateIcarFertilizer(input: FertilizationInput): FertilizationResult {
  const pop = ICAR_POP_REGISTRY["MH_SUGARCANE_ADSALI"]; // MPKV Rahuri PoP 2023-24
  
  // Guardrail 1: Missing Soil Health Card data triggers mandatory test
  if (input.shcAvailableN_kg_ha === null || input.shcAvailableP_kg_ha === null) {
    return { status: "NEEDS_SOIL_TEST", ureaBags: 0, dapBags: 0, mopBags: 0 };
  }

  // Guardrail 2: All deficits computed per hectare first to prevent unit mixing
  const deficitN_ha = Math.min(pop.targetN_kg_ha, Math.max(0, pop.targetN_kg_ha - input.shcAvailableN_kg_ha));
  const deficitP_ha = Math.min(pop.targetP2O5_kg_ha, Math.max(0, pop.targetP2O5_kg_ha - input.shcAvailableP_kg_ha));
  const deficitK_ha = Math.min(pop.targetK2O_kg_ha, Math.max(0, pop.targetK2O_kg_ha - input.shcAvailableK_kg_ha));

  // Guardrail 3: Standard commercial grades (DAP 18% N, 46% P2O5; Urea 46% N 45kg bag)
  const dapBags_ha = deficitP_ha / (50 * 0.46);
  const nFromDap_ha = dapBags_ha * 50 * 0.18;
  const remainingN_ha = Math.max(0, deficitN_ha - nFromDap_ha);
  const ureaBags_ha = remainingN_ha / (45 * 0.46);
  const mopBags_ha = deficitK_ha / (50 * 0.60);

  // Convert to plot area at the very end (1 ha = 2.47 acres)
  const plotHa = input.plotAcres / 2.47;
  return {
    status: "VERIFIED_SAFE_CALCULATION",
    ureaBags: Number((ureaBags_ha * plotHa).toFixed(1)), // 2.1 bags Urea
    dapBags: Number((dapBags_ha * plotHa).toFixed(1)),   // 1.2 bags DAP
    mopBags: 0, // Soil saturated with potassium (saves ₹1,840)
  };
}`,
    profit: `// -------------------------------------------------------------
// DETERMINISTIC MANDI PRICE & NET FARM-GATE REALIZATION ENGINE
// Source: Agmarknet via data.gov.in OGD API
// Net Realization = APMC Modal Price - (Road Distance * Freight Rate)
// -------------------------------------------------------------
export function calculateMandiNetRealization(
  apmcCandidates: Array<{ name: string; modalPrice: number; distanceKm: number }>,
  cropQuintals: number
) {
  const FREIGHT_PER_KM_QTL = 2.35; // Standard rural freight benchmark (INR/km/qtl)

  const rankedMandis = apmcCandidates.map((mandi) => {
    const transitCostPerQtl = Number((mandi.distanceKm * FREIGHT_PER_KM_QTL).toFixed(2));
    const netPerQtl = mandi.modalPrice - transitCostPerQtl;
    return {
      mandi: mandi.name,
      distanceKm: mandi.distanceKm,
      modalPrice: mandi.modalPrice,
      freightPerQtl: transitCostPerQtl,
      netPerQtl,
      totalNetRealization: Math.round(netPerQtl * cropQuintals),
    };
  });

  return rankedMandis.sort((a, b) => b.netPerQtl - a.netPerQtl);
}`,
    labor: `// -------------------------------------------------------------
// CROSS-FACTOR HARVEST & SPRAY SCHEDULER (TypeScript Rule Engine)
// Checks weather forecast, soil moisture, and available worker slots
// -------------------------------------------------------------
export function evaluateFieldOperation(
  rainStartHour: number,      // e.g. 11 (11:00 AM)
  windSpeedKmh: number,       // e.g. 8 km/h (< 12 km/h safe)
  workersAvailableAm: number, // e.g. 2 workers
  soilMoisturePct: number     // e.g. 38%
) {
  const canSpray = rainStartHour >= 11 && windSpeedKmh <= 12 && workersAvailableAm >= 1;
  const skipIrrigation = soilMoisturePct >= 35; // Adequate root zone moisture

  return {
    action: canSpray ? "Spray approved 6:30–9:00 AM" : "Do not spray today",
    factors: [
      { name: "Rain Forecast", status: rainStartHour >= 11 ? "PASS" : "FAIL", detail: "Dry till 11 AM" },
      { name: "Wind Speed", status: windSpeedKmh <= 12 ? "PASS" : "FAIL", detail: \`\${windSpeedKmh} km/h (Calm)\` },
      { name: "Labour Slot", status: workersAvailableAm >= 1 ? "PASS" : "FAIL", detail: \`\${workersAvailableAm} workers ready\` },
      { name: "Soil Moisture", status: "INFO", detail: \`\${soilMoisturePct}% (Skip watering)\` },
    ],
    explanationPromptConstraint: "LLM must quote exactly 6:30–9:00 AM, 38% moisture, and 2 workers."
  };
}`,
  };

  return (
    <div className="space-y-8">
      {/* Header and Parcel Selector */}
      <div className="web2-panel p-4 rounded-lg border border-zinc-300 bg-white shadow-sm flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="w-2.5 h-2.5 rounded bg-zinc-900"></span>
            <h3 className="font-bold text-sm text-zinc-900">
              Interactive System Architecture: Parallel Telemetry to Deterministic Math
            </h3>
            <span className="web2-badge text-[10px] font-mono py-0.5 px-2 bg-emerald-50 text-emerald-800 border-emerald-300">
              Live Diagram (Images 2 &amp; 3)
            </span>
          </div>
          <p className="text-xs text-zinc-600 font-sans mt-0.5">
            Test how a farmer&apos;s mobile GPS pin triggers 5 parallel data feeds before passing into an isolated ICAR math engine.
          </p>
        </div>

        {/* Parcel selector pill tabs */}
        <div className="flex items-center gap-1.5 text-xs font-mono">
          <span className="text-zinc-500 text-[11px] mr-1 hidden sm:inline">Test Plot:</span>
          {parcels.map((p) => (
            <button
              key={p.id}
              onClick={() => setSelectedParcel(p)}
              className={`px-2.5 py-1 rounded border text-xs transition-colors ${
                selectedParcel.id === p.id
                  ? "bg-zinc-900 text-white border-zinc-900 font-bold shadow-sm"
                  : "bg-white text-zinc-700 border-zinc-300 hover:bg-zinc-100"
              }`}
            >
              {p.location.split(",")[0]}
            </button>
          ))}
        </div>
      </div>

      {/* ------------------------------------------------------------- */}
      {/* DIAGRAM SECTION 1: PARALLEL API TELEMETRY LAYER (IMAGE 2)     */}
      {/* ------------------------------------------------------------- */}
      <div className="web2-panel rounded-lg border border-zinc-300 bg-zinc-50 p-5 shadow-sm space-y-4">
        <div className="flex items-center justify-between border-b border-zinc-200 pb-2.5">
          <div className="flex items-center gap-2">
            <span className="text-xs font-mono font-bold uppercase text-zinc-500">STAGE 01</span>
            <span className="text-sm font-bold text-zinc-900">
              Data Ingestion &amp; Parallel API Telemetry Layer
            </span>
          </div>
          <span className="text-xs font-mono text-emerald-700 bg-emerald-100 px-2 py-0.5 rounded font-semibold">
            Sub-400ms Parallel Execution
          </span>
        </div>

        {/* The Fan-Out Visualizer: GPS PIN fanning out to 5 parallel APIs */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-4 items-center">
          {/* Origin Node: GPS Pin Box */}
          <div className="lg:col-span-4 p-4 rounded-lg border-2 border-zinc-900 bg-white shadow-tactile space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-xs font-mono font-bold text-zinc-900 flex items-center gap-1.5">
                <MapPin className="w-4 h-4 text-red-600" />
                <span>[ GPS Pin: Lat, Long ]</span>
              </span>
              <span className="w-2 h-2 rounded-full bg-emerald-600 animate-ping"></span>
            </div>

            <div className="text-xs font-mono space-y-1 pt-1 border-t border-zinc-200">
              <div className="text-zinc-800 font-bold">{selectedParcel.coordinates}</div>
              <div className="text-zinc-600">{selectedParcel.location}</div>
              <div className="text-[11px] text-zinc-500">Soil: {selectedParcel.soil}</div>
              <div className="text-[11px] text-zinc-500">Crop: {selectedParcel.crop}</div>
            </div>

            <div className="pt-2 flex items-center justify-between text-[11px] font-mono text-emerald-800 bg-emerald-50 p-1.5 rounded border border-emerald-200">
              <span>Concurrent Fan-Out:</span>
              <strong>5 APIs Parallel</strong>
            </div>
          </div>

          {/* Fan-Out Arrow indicator */}
          <div className="lg:col-span-1 flex lg:flex-col items-center justify-center text-zinc-400 py-1">
            <ArrowRight className="w-6 h-6 text-zinc-800 hidden lg:block" />
            <ArrowDown className="w-6 h-6 text-zinc-800 lg:hidden" />
          </div>

          {/* 5 Parallel API Target Nodes (Image 2 Direct Representation) */}
          <div className="lg:col-span-7 space-y-2">
            {parallelApis.map((api, idx) => {
              const isSelected = activeApi === idx;
              return (
                <div
                  key={idx}
                  onClick={() => setActiveApi(idx)}
                  className={`cursor-pointer p-2.5 rounded border transition-all text-xs font-mono flex items-center justify-between gap-2 ${
                    isSelected
                      ? "bg-white border-zinc-800 shadow-sm"
                      : "bg-zinc-100 border-zinc-300 hover:bg-white hover:border-zinc-400"
                  }`}
                >
                  <div className="flex items-center gap-2 min-w-0">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-600 shrink-0"></span>
                    <strong className="text-zinc-900 truncate">{api.name}</strong>
                  </div>

                  <div className="flex items-center gap-2 shrink-0 text-[11px]">
                    <span className="text-zinc-500 hidden sm:inline">{api.source.split(" ")[0]}</span>
                    <span className="px-1.5 py-0.5 rounded bg-zinc-200 text-zinc-700 text-[10px]">
                      {api.protocol.split(" ")[0]}
                    </span>
                    <span className="text-emerald-700 font-bold">Live Ingest</span>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Interactive Drawer for Selected Parallel API Data Payload */}
        {parallelApis[activeApi] && (
          <div className="bg-zinc-900 text-zinc-100 p-3.5 rounded-md font-mono text-xs space-y-1.5 border border-zinc-800">
            <div className="flex items-center justify-between text-zinc-400 text-[11px] border-b border-zinc-800 pb-1">
              <span>
                ACTIVE TELEMETRY PAYLOAD: {parallelApis[activeApi].name}
              </span>
              <span className="text-emerald-400">STATUS: 200 OK</span>
            </div>
            <p className="text-zinc-300 text-xs font-sans">
              <strong>Purpose:</strong> {parallelApis[activeApi].purpose}
            </p>
            <div className="bg-zinc-950 p-2 rounded text-emerald-400 text-[11px] overflow-x-auto">
              <code>{parallelApis[activeApi].sampleOutput}</code>
            </div>
          </div>
        )}
      </div>

      {/* Downward Transition Arrow */}
      <div className="flex items-center justify-center">
        <div className="flex items-center gap-2 bg-zinc-200 px-3 py-1 rounded-full text-xs font-mono text-zinc-700 border border-zinc-300">
          <ArrowDown className="w-4 h-4 text-zinc-900" />
          <span>Ingested Telemetry Passed to Isolated Code Guardrails</span>
        </div>
      </div>

      {/* ------------------------------------------------------------- */}
      {/* DIAGRAM SECTION 2: DETERMINISTIC MATH ENGINE (IMAGE 3 TOP)   */}
      {/* ------------------------------------------------------------- */}
      <div className="web2-panel rounded-lg border border-zinc-300 bg-white p-5 shadow-sm space-y-4">
        <div className="flex items-center justify-between border-b border-zinc-200 pb-2.5">
          <div className="flex items-center gap-2">
            <span className="text-xs font-mono font-bold uppercase text-zinc-500">STAGE 02</span>
            <span className="text-sm font-bold text-zinc-900">
              Deterministic Rule Engine Guardrails (Rule-Based Dosage Verification)
            </span>
          </div>
          <span className="text-xs font-mono text-amber-900 bg-amber-100 px-2 py-0.5 rounded font-semibold flex items-center gap-1">
            <Lock className="w-3 h-3 text-amber-700" />
            <span>LLM Barred From Math</span>
          </span>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-5 items-start">
          {/* Left: Code Box and Logic Tabs */}
          <div className="lg:col-span-8 space-y-3">
            {/* Math Code Selector Tabs */}
            <div className="flex items-center gap-2 text-xs font-mono border-b border-zinc-200 pb-2">
              <button
                onClick={() => setActiveCodeTab("nutrient")}
                className={`px-3 py-1 rounded border transition-colors ${
                  activeCodeTab === "nutrient"
                    ? "bg-zinc-900 text-white border-zinc-900 font-bold"
                    : "bg-zinc-100 text-zinc-700 border-zinc-300 hover:bg-zinc-200"
                }`}
              >
                1. ICAR Nutrient Balance
              </button>
              <button
                onClick={() => setActiveCodeTab("profit")}
                className={`px-3 py-1 rounded border transition-colors ${
                  activeCodeTab === "profit"
                    ? "bg-zinc-900 text-white border-zinc-900 font-bold"
                    : "bg-zinc-100 text-zinc-700 border-zinc-300 hover:bg-zinc-200"
                }`}
              >
                2. Net Farm-Gate Profit
              </button>
              <button
                onClick={() => setActiveCodeTab("labor")}
                className={`px-3 py-1 rounded border transition-colors ${
                  activeCodeTab === "labor"
                    ? "bg-zinc-900 text-white border-zinc-900 font-bold"
                    : "bg-zinc-100 text-zinc-700 border-zinc-300 hover:bg-zinc-200"
                }`}
              >
                3. Labor &amp; Spray Scheduler
              </button>
            </div>

            {/* TypeScript Code Display */}
            <div className="bg-zinc-950 text-zinc-200 p-3.5 rounded-lg font-mono text-xs overflow-x-auto border border-zinc-800 shadow-inner">
              <div className="flex items-center justify-between text-zinc-500 text-[10px] border-b border-zinc-800 pb-1 mb-2">
                <span>FILE: lib/icar-fertilizer.ts</span>
                <span className="text-emerald-400">TYPESCRIPT / NODE.JS DETERMINISTIC LAYER</span>
              </div>
              <pre className="text-zinc-200 leading-relaxed font-mono">
                {typescriptMathCode[activeCodeTab]}
              </pre>
            </div>
          </div>

          {/* Right: The Verified Safe Output Box (Image 3 Representation) */}
          <div className="lg:col-span-4 space-y-3">
            <div className="p-4 rounded-lg border-2 border-emerald-600 bg-emerald-50/70 shadow-sm space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-xs font-mono font-bold text-emerald-950 flex items-center gap-1.5">
                  <ShieldCheck className="w-4 h-4 text-emerald-700" />
                  <span>VERIFIED RULE CALCULATION</span>
                </span>
                <span className="web2-badge web2-badge-green text-[10px] py-0 px-2">PASS</span>
              </div>

              <div className="bg-white p-3 rounded border border-emerald-300 space-y-2 font-mono text-xs">
                <div className="text-zinc-500 text-[10px] uppercase">Rule Engine Output (2.5 Acre Plot):</div>
                <div className="text-emerald-950 font-bold text-sm">
                  &quot;Apply 2.1 bags Urea&quot;
                </div>
                <div className="text-zinc-700 text-xs font-sans">
                  • 1.2 bags DAP for root establishment
                  <br />
                  • 0.0 bags Potash (K saturated in soil)
                  <br />• Spray restricted 11:00 AM onwards (rain)
                </div>
              </div>

              <p className="text-[11px] text-emerald-900 font-sans leading-relaxed">
                By decoupling mathematics from the generative LLM, KrishiSmriti computes all chemical dosages through a deterministic rule engine, never generating them via LLM.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Downward Transition Arrow */}
      <div className="flex items-center justify-center">
        <div className="flex items-center gap-2 bg-zinc-200 px-3 py-1 rounded-full text-xs font-mono text-zinc-700 border border-zinc-300">
          <ArrowDown className="w-4 h-4 text-zinc-900" />
          <span>Calculations &amp; Filtered RAG Chunks Fed into Reasoning Pipeline</span>
        </div>
      </div>

      {/* ------------------------------------------------------------- */}
      {/* DIAGRAM SECTION 3: SYNTHESIS & LOCALIZATION (IMAGE 3 BOTTOM) */}
      {/* ------------------------------------------------------------- */}
      <div className="web2-panel rounded-lg border border-zinc-300 bg-zinc-900 text-white p-5 shadow-md space-y-4">
        <div className="flex items-center justify-between border-b border-zinc-800 pb-2.5">
          <div className="flex items-center gap-2">
            <span className="text-xs font-mono font-bold uppercase text-zinc-400">STAGE 03</span>
            <span className="text-sm font-bold text-white">
              Synthesis, Reasoning &amp; Vernacular Localization Engine
            </span>
          </div>
          <span className="text-xs font-mono text-emerald-400 bg-emerald-950/80 border border-emerald-700 px-2 py-0.5 rounded">
            Bhashini Indic Voice Note Output
          </span>
        </div>

        {/* Pipeline Strip directly reflecting Image 3 bottom */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-3 text-xs font-mono text-center">
          {/* Step 1 */}
          <div className="bg-zinc-800/80 p-3 rounded border border-zinc-700 space-y-1">
            <span className="text-[10px] text-zinc-400 block uppercase">1. Input Context</span>
            <div className="text-white font-bold text-xs">[ Aggregated Context + Rule Results + RAG Chunks ]</div>
          </div>

          {/* Step 2 */}
          <div className="bg-zinc-800/80 p-3 rounded border border-zinc-700 space-y-1">
            <span className="text-[10px] text-zinc-400 block uppercase">2. LLM Reasoning</span>
            <div className="text-white font-bold text-xs">[ LLM Prompt Pipeline (Strict JSON) ]</div>
          </div>

          {/* Step 3 */}
          <div className="bg-zinc-800/80 p-3 rounded border border-zinc-700 space-y-1">
            <span className="text-[10px] text-zinc-400 block uppercase">3. Translation</span>
            <div className="text-white font-bold text-xs">[ Regional Marathi (Pune) / Hindi ]</div>
          </div>

          {/* Step 4 */}
          <div className="bg-emerald-950/70 p-3 rounded border border-emerald-600 text-emerald-200 space-y-1">
            <span className="text-[10px] text-emerald-400 block uppercase">4. Speech Synthesis</span>
            <div className="text-white font-bold text-xs flex items-center justify-center gap-1">
              <Volume2 className="w-3.5 h-3.5 text-emerald-400" />
              <span>[ Native Audio (Bhashini) ]</span>
            </div>
          </div>
        </div>

        {/* Final Voice Note Output Card */}
        <div className="bg-zinc-950 p-4 rounded border border-zinc-800 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
          <div className="space-y-1 font-sans">
            <div className="flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
              <span className="font-mono text-xs text-emerald-400 font-bold">
                GENERATED ACTIONABLE AUDIO NOTE (Bhashini Voice):
              </span>
            </div>
            <p className="text-xs text-zinc-300 italic">
              &quot;राम-राम रामू भाऊ! उद्या सकाळी ११ वाजता पाऊस सुरू होणार आहे, पण सकाळी ९ पर्यंत वारा शांत आहे आणि २ मजूर उपलब्ध आहेत. त्यामुळे उद्या सकाळी ६:३० ते ९ या वेळेतच फवारणी करा. जमिनीत ओलावा ३८% असल्याने पाणी देणे पुढे ढकला.&quot;
            </p>
            <p className="text-[11px] text-zinc-400">
              English Translation: &quot;Namaste Ramu-ji! Rain starts at 11:00 AM tomorrow, but winds remain calm until 9:00 AM with 2 workers available. Spray between 6:30–9:00 AM; skip irrigation as soil moisture is at 38%.&quot;
            </p>
          </div>

          <div className="shrink-0 font-mono text-[11px] text-zinc-400 bg-zinc-900 px-3 py-1.5 rounded border border-zinc-800">
            Bhashini Indic TTS · Audio Playback
          </div>
        </div>
      </div>
    </div>
  );
};
