/**
 * =============================================================================
 * DETERMINISTIC ICAR NUTRIENT BALANCE & FERTILIZER CALCULATION ENGINE
 * Grounded in ICAR Package of Practices (PoP) & State Agricultural University Standards
 * (e.g., MPKV Rahuri recommendations for Maharashtra sugarcane and cereals)
 * =============================================================================
 *
 * Rules:
 * 1. Computations are strictly deterministic (TypeScript rule engine, NEVER generated by LLM).
 * 2. Per-hectare first: all deficits are computed per hectare, bag counts per hectare,
 *    then converted to the plot area once at the end (1 hectare = 2.47105 acres).
 * 3. Commercial fertilizer grades:
 *    - Urea: 46% N (standard 45 kg bag)
 *    - DAP (Di-Ammonium Phosphate): 18% N and 46% P₂O₅ (standard 50 kg bag)
 *    - MOP (Muriate of Potash): 60% K₂O (standard 50 kg bag)
 * 4. P and K are strictly measured and expressed as P₂O₅ and K₂O (matching fertilizer grades).
 * 5. Upper caps: Dosages are capped at the official PoP maximum to prevent chemical burning.
 * 6. Missing Soil Health Card (SHC) data: explicitly returns "NEEDS_SOIL_TEST" rather than guessing.
 */

export interface SoilNutrientProfile {
  availableN_kg_ha: number | null;     // Available Nitrogen (kg/ha)
  availableP2O5_kg_ha: number | null;  // Available P₂O₅ (kg/ha)
  availableK2O_kg_ha: number | null;   // Available K₂O (kg/ha)
  soilType?: string;                   // e.g. "Black Cotton Soil (Vertisol)"
  ph?: number;
  organicCarbon_pct?: number;
  testDate?: string;
}

export interface CropNutrientTarget {
  cropName: string;
  variety?: string;
  season: "Kharif" | "Rabi" | "Zaid" | "Annual / Perennial";
  state: string;
  sourceDoc: string;                   // e.g. "MPKV Rahuri Sugarcane Package of Practices 2024-25"
  recommendedN_kg_ha: number;
  recommendedP2O5_kg_ha: number;
  recommendedK2O_kg_ha: number;
  maxCapN_kg_ha: number;
  maxCapP2O5_kg_ha: number;
  maxCapK2O_kg_ha: number;
  splits: {
    basalN_pct: number;
    basalP2O5_pct: number;
    basalK2O_pct: number;
  };
}

export interface FertilizerDoseResult {
  status: "SUCCESS" | "NEEDS_SOIL_TEST" | "ZERO_DEFICIT" | "INVALID_PLOT_SIZE";
  message: string;
  plotAcres: number;
  plotHectares: number;
  crop: string;
  sourceCitation: string;
  perHectare: {
    deficitN_kg: number;
    deficitP2O5_kg: number;
    deficitK2O_kg: number;
    dapBags: number;
    ureaBags: number;
    mopBags: number;
  };
  totalPlotRequirement: {
    dapBags: number;
    ureaBags: number;
    mopBags: number;
    dapKg: number;
    ureaKg: number;
    mopKg: number;
  };
  basalDoseImmediate: {
    dapBags: number;
    ureaBags: number;
    mopBags: number;
  };
  advisories: string[];
}

/**
 * Versioned Package of Practices Nutrient Target Registry
 */
export const ICAR_POP_REGISTRY: Record<string, CropNutrientTarget> = {
  "maharashtra_sugarcane_annual": {
    cropName: "Sugarcane (Suru / Adsali / Pre-seasonal)",
    variety: "Co-86032 / CoM-0265",
    season: "Annual / Perennial",
    state: "Maharashtra",
    sourceDoc: "MPKV Rahuri Agricultural University PoP 2024, Bul. No. 42",
    recommendedN_kg_ha: 250,
    recommendedP2O5_kg_ha: 115,
    recommendedK2O_kg_ha: 115,
    maxCapN_kg_ha: 300,
    maxCapP2O5_kg_ha: 125,
    maxCapK2O_kg_ha: 125,
    splits: {
      basalN_pct: 0.10,
      basalP2O5_pct: 0.50,
      basalK2O_pct: 0.50,
    },
  },
  "maharashtra_soybean_kharif": {
    cropName: "Soybean",
    variety: "JS-335 / MAUS-71",
    season: "Kharif",
    state: "Maharashtra",
    sourceDoc: "VNMKV Parbhani & ICAR-IISR Indore PoP 2023",
    recommendedN_kg_ha: 30,
    recommendedP2O5_kg_ha: 60,
    recommendedK2O_kg_ha: 30,
    maxCapN_kg_ha: 40,
    maxCapP2O5_kg_ha: 80,
    maxCapK2O_kg_ha: 40,
    splits: {
      basalN_pct: 1.0,
      basalP2O5_pct: 1.0,
      basalK2O_pct: 1.0,
    },
  },
  "up_wheat_rabi": {
    cropName: "Wheat",
    variety: "PBW-502 / HD-2967",
    season: "Rabi",
    state: "Uttar Pradesh",
    sourceDoc: "ICAR-IIWBR Karnal & CSAUA&T Kanpur Advisory Guidelines 2024",
    recommendedN_kg_ha: 120,
    recommendedP2O5_kg_ha: 60,
    recommendedK2O_kg_ha: 40,
    maxCapN_kg_ha: 150,
    maxCapP2O5_kg_ha: 75,
    maxCapK2O_kg_ha: 50,
    splits: {
      basalN_pct: 0.50,
      basalP2O5_pct: 1.0,
      basalK2O_pct: 1.0,
    },
  },
};

/**
 * Calculates scientifically sound fertilizer dosages using per-hectare first methodology.
 *
 * @param cropTargetKey Key matching ICAR_POP_REGISTRY (defaults to "maharashtra_sugarcane_annual")
 * @param shc Soil Nutrient Profile from Soil Health Card
 * @param plotAcres Plot size in acres
 */
export function calculateIcarFertilizer(
  cropTargetKey: string,
  shc: SoilNutrientProfile,
  plotAcres: number
): FertilizerDoseResult {
  const cropTarget = ICAR_POP_REGISTRY[cropTargetKey] || ICAR_POP_REGISTRY["maharashtra_sugarcane_annual"];

  // 1. Validation: Plot size must be positive
  if (!plotAcres || plotAcres <= 0) {
    return {
      status: "INVALID_PLOT_SIZE",
      message: "Plot size must be greater than 0 acres.",
      plotAcres: 0,
      plotHectares: 0,
      crop: cropTarget.cropName,
      sourceCitation: cropTarget.sourceDoc,
      perHectare: { deficitN_kg: 0, deficitP2O5_kg: 0, deficitK2O_kg: 0, dapBags: 0, ureaBags: 0, mopBags: 0 },
      totalPlotRequirement: { dapBags: 0, ureaBags: 0, mopBags: 0, dapKg: 0, ureaKg: 0, mopKg: 0 },
      basalDoseImmediate: { dapBags: 0, ureaBags: 0, mopBags: 0 },
      advisories: ["Please provide a valid plot acreage to calculate dosages."],
    };
  }

  // 2. Validation: Check for missing critical Soil Health Card data
  if (
    shc.availableN_kg_ha === null ||
    shc.availableP2O5_kg_ha === null ||
    shc.availableK2O_kg_ha === null
  ) {
    return {
      status: "NEEDS_SOIL_TEST",
      message: "Soil Health Card test values missing. A physical soil test is required before chemical recommendations.",
      plotAcres,
      plotHectares: plotAcres / 2.47105,
      crop: cropTarget.cropName,
      sourceCitation: cropTarget.sourceDoc,
      perHectare: { deficitN_kg: 0, deficitP2O5_kg: 0, deficitK2O_kg: 0, dapBags: 0, ureaBags: 0, mopBags: 0 },
      totalPlotRequirement: { dapBags: 0, ureaBags: 0, mopBags: 0, dapKg: 0, ureaKg: 0, mopKg: 0 },
      basalDoseImmediate: { dapBags: 0, ureaBags: 0, mopBags: 0 },
      advisories: [
        "No chemical dosage is generated without verified Soil Health Card baseline data.",
        "Consult your nearest Krishi Vigyan Kendra (KVK) or Gram Panchayat CSC for a 12-parameter soil test.",
      ],
    };
  }

  // 3. STEP 1: Compute Per-Hectare Nutrient Deficits (capped at PoP maximum)
  const rawDeficitN = Math.max(0, cropTarget.recommendedN_kg_ha - shc.availableN_kg_ha);
  const rawDeficitP = Math.max(0, cropTarget.recommendedP2O5_kg_ha - shc.availableP2O5_kg_ha);
  const rawDeficitK = Math.max(0, cropTarget.recommendedK2O_kg_ha - shc.availableK2O_kg_ha);

  const deficitN_ha = Math.min(rawDeficitN, cropTarget.maxCapN_kg_ha);
  const deficitP2O5_ha = Math.min(rawDeficitP, cropTarget.maxCapP2O5_kg_ha);
  const deficitK2O_ha = Math.min(rawDeficitK, cropTarget.maxCapK2O_kg_ha);

  // 4. STEP 2: Compute Per-Hectare Commercial Fertilizer Quantities
  // Commercial Grades:
  // - DAP: 18% N, 46% P₂O₅ in 50 kg bags (9 kg N + 23 kg P₂O₅ per bag)
  // - Urea: 46% N in 45 kg bags (20.7 kg N per bag)
  // - MOP: 60% K₂O in 50 kg bags (30 kg K₂O per bag)

  // A. P requirement fulfilled through DAP first:
  const dapKg_ha = deficitP2O5_ha > 0 ? deficitP2O5_ha / 0.46 : 0;
  const dapBags_ha = dapKg_ha / 50.0;

  // B. Nitrogen supplied by DAP:
  const nSuppliedByDap_ha = dapKg_ha * 0.18;

  // C. Remaining Nitrogen deficit fulfilled through Urea:
  const remainingN_ha = Math.max(0, deficitN_ha - nSuppliedByDap_ha);
  const ureaKg_ha = remainingN_ha > 0 ? remainingN_ha / 0.46 : 0;
  const ureaBags_ha = ureaKg_ha / 45.0;

  // D. Potassium requirement fulfilled through MOP:
  const mopKg_ha = deficitK2O_ha > 0 ? deficitK2O_ha / 0.60 : 0;
  const mopBags_ha = mopKg_ha / 50.0;

  // 5. STEP 3: Scale from Per-Hectare to Farmer's Exact Plot Area
  const plotHectares = plotAcres / 2.47105;

  const totalDapBags = Math.round(dapBags_ha * plotHectares * 10) / 10;
  const totalUreaBags = Math.round(ureaBags_ha * plotHectares * 10) / 10;
  const totalMopBags = Math.round(mopBags_ha * plotHectares * 10) / 10;

  const totalDapKg = Math.round(dapKg_ha * plotHectares);
  const totalUreaKg = Math.round(ureaKg_ha * plotHectares);
  const totalMopKg = Math.round(mopKg_ha * plotHectares);

  // 6. Basal Application (Split scheduling based on PoP)
  const basalDapBags = Math.round(totalDapBags * cropTarget.splits.basalP2O5_pct * 10) / 10;
  const basalUreaBags = Math.round(totalUreaBags * cropTarget.splits.basalN_pct * 10) / 10;
  const basalMopBags = Math.round(totalMopBags * cropTarget.splits.basalK2O_pct * 10) / 10;

  // 7. Contextual Advisories
  const advisories: string[] = [];

  if (totalDapBags === 0 && totalUreaBags === 0 && totalMopBags === 0) {
    advisories.push("Soil nutrient reserves exceed crop requirements. Zero synthetic fertilizers required for this cycle.");
  } else {
    advisories.push(`Apply ${basalDapBags} bags DAP, ${basalUreaBags} bags Urea, and ${basalMopBags} bags Potash as basal dose.`);
  }

  if (deficitK2O_ha === 0) {
    advisories.push(`Potash application omitted: soil test indicates surplus K₂O (${shc.availableK2O_kg_ha} kg/ha).`);
  }

  if (shc.ph && shc.ph > 8.2) {
    advisories.push(`Alkaline soil (pH ${shc.ph.toFixed(1)}): Incorporate gypsum or farmyard manure (FYM) before planting.`);
  }

  return {
    status: totalDapBags === 0 && totalUreaBags === 0 && totalMopBags === 0 ? "ZERO_DEFICIT" : "SUCCESS",
    message: "Fertilizer dosage verified against ICAR & State Agricultural University Package of Practices.",
    plotAcres,
    plotHectares: Math.round(plotHectares * 100) / 100,
    crop: cropTarget.cropName,
    sourceCitation: cropTarget.sourceDoc,
    perHectare: {
      deficitN_kg: Math.round(deficitN_ha),
      deficitP2O5_kg: Math.round(deficitP2O5_ha),
      deficitK2O_kg: Math.round(deficitK2O_ha),
      dapBags: Math.round(dapBags_ha * 10) / 10,
      ureaBags: Math.round(ureaBags_ha * 10) / 10,
      mopBags: Math.round(mopBags_ha * 10) / 10,
    },
    totalPlotRequirement: {
      dapBags: totalDapBags,
      ureaBags: totalUreaBags,
      mopBags: totalMopBags,
      dapKg: totalDapKg,
      ureaKg: totalUreaKg,
      mopKg: totalMopKg,
    },
    basalDoseImmediate: {
      dapBags: basalDapBags,
      ureaBags: basalUreaBags,
      mopBags: basalMopBags,
    },
    advisories,
  };
}
