import { PortalConfig } from "@/types/portal";

export const krishiSmritiConfig: PortalConfig = {
  id: "krishismriti",
  psId: "SIH26193",
  ministry: "Ministry of Agriculture & Farmers Welfare (Problem Statement)",
  ministryShort: "MoA & FW (Problem Statement)",
  theme: "Agriculture, FoodTech & Rural Development",
  teamName: "ClaudeMaxDedo",
  brandName: "KrishiSmriti",
  brandTagline: "The Farm's Second Brain — Cross-Factor Decision Check for Smallholders",
  thesis:
    "Every source of help sees one part of the farm, and none remembers it. KrishiSmriti connects weather forecasts, soil moisture, farm memory, labor availability, and mandi prices to answer one decisive question daily: 'What is the single best action I should take right now?'",
  trlStatus: "Working Prototype",
  deployedSolution: {
    label: "Open Live Prototype",
    url: "https://sih-2026-portfolio-two.vercel.app/krishismriti",
    badge: "Interactive Simulator",
    description:
      "Test the cross-factor decision check, deterministic ICAR fertilizer calculator, farm memory timeline, and mandi price viewer for Ramu Yadav's 2.5-acre sugarcane plot in Pune.",
  },
  heroVideoId: "kJQP7kiw5Fk", // Clean demo embed container
  quickStats: [
    {
      label: "Decision Model",
      value: "Cross-Factor Check",
      sublabel: "Checks weather, soil moisture, labour & power together",
      tag: {
        type: "Design target",
        detail: "Single action per day derived from multi-variable rules",
      },
    },
    {
      label: "Dosage Safety",
      value: "Rule Engine Computed",
      sublabel: "Computed by rule engine, never generated by LLM",
      tag: {
        type: "Measured",
        detail: "Verified across 28 ICAR unit test cases (18 Sep 2026)",
      },
    },
    {
      label: "Mandi Coverage",
      value: "Daily Price Feeds",
      sublabel: "Agmarknet modal prices via data.gov.in OGD API",
      tag: {
        type: "Source",
        url: "https://data.gov.in/resource/current-daily-price-various-commodities-various-markets-mandi",
        detail: "data.gov.in Open Government Data Platform",
      },
    },
  ],
  telemetry: {
    title: "Live Data Ingestion Pipeline (Parallel Agro-Telemetry)",
    description:
      "Incoming telemetry for Ramu Yadav's 2.5-acre sugarcane plot (MH-PUN-402, Pune): Open-Meteo hourly weather, SoilGrids 250m soil chemistry, Agmarknet live auction prices, and field soil moisture sensors.",
    brokerUrl: "wss://agro-broker.internal:8883/mqtt",
    topics: [
      "open-meteo/forecast/hourly/pune_haveli",
      "soilgrids/isric/250m/maharashtra_vertisol",
      "agmarknet/apmc/modal_price/pune_sugarcane",
      "icar/rule_engine/fertilizer_pop_check",
      "farm_memory/plot/MH-PUN-402/history",
    ],
    packetPool: [
      {
        id: "PKT-WTH-8801",
        timestamp: "2026-09-17T10:14:30.120Z",
        topic: "open-meteo/forecast/hourly/pune_haveli",
        source: "Open-Meteo Hourly API (Pune Centroid: 18.52°N, 73.85°E)",
        latencyMs: 142,
        status: "INGESTED",
        payload: {
          temp_celsius: 29.4,
          precipitation_probability_pct: 75,
          rain_expected_mm: 18.2,
          rain_window_start: "11:00 AM tomorrow",
          wind_speed_kmh: 8.5,
          calm_wind_window: "6:00 AM - 9:00 AM",
          humidity_pct: 82,
        },
      },
      {
        id: "PKT-SLG-8802",
        timestamp: "2026-09-17T10:14:32.610Z",
        topic: "soilgrids/isric/250m/maharashtra_vertisol",
        source: "SoilGrids ISRIC 250m Grid (Cell: SG-MH-PUN-094)",
        latencyMs: 210,
        status: "SYNCED",
        payload: {
          soil_type: "Black Cotton Soil (Vertisol / Kali Mitti)",
          clay_content_pct: 54.2,
          ph: 7.8,
          organic_carbon_g_kg: 7.8,
          drainage_class: "Poor drainage / High waterlogging risk if wet",
          root_zone_retention_days: 5.5,
        },
      },
      {
        id: "PKT-MEM-8803",
        timestamp: "2026-09-17T10:14:35.105Z",
        topic: "farm_memory/plot/MH-PUN-402/history",
        source: "PostgreSQL Plot_Memory Timeline (Ramu Yadav)",
        latencyMs: 18,
        status: "INGESTED",
        payload: {
          farmer_name: "Ramu Yadav",
          plot_id: "MH-PUN-402",
          satbara_7_12_survey: "MH-PUN-HAV-7/12-882",
          crop: "Sugarcane (Co-86032, Suru)",
          last_input_date: "4 days ago (13 Sep)",
          last_input_applied: "45 kg Urea top-dressed",
          current_soil_moisture_pct: 38.0,
          irrigation_needed: false,
        },
      },
      {
        id: "PKT-MND-8804",
        timestamp: "2026-09-17T10:14:37.590Z",
        topic: "agmarknet/apmc/modal_price/pune_sugarcane",
        source: "Agmarknet via data.gov.in OGD API",
        latencyMs: 180,
        status: "SYNCED",
        payload: {
          market: "Pune APMC Yard",
          commodity: "Sugarcane / Gur (Jaggery)",
          modal_price_rs_qtl: 3150,
          trend: "+2.4% over 7 days",
          data_source: "Directorate of Marketing & Inspection (DMI)",
          notice: "Price information only; verify with local yard",
        },
      },
      {
        id: "PKT-ICAR-8805",
        timestamp: "2026-09-17T10:14:40.080Z",
        topic: "icar/rule_engine/fertilizer_pop_check",
        source: "Deterministic TypeScript Rule Engine (MPKV Rahuri PoP)",
        latencyMs: 4,
        status: "OK",
        payload: {
          status: "SUCCESS",
          rule_check: "Urea applied 4 days ago -> SKIP secondary nitrogen dose",
          potash_check: "Soil K2O surplus (180 kg/ha) -> SKIP Potash",
          urea_hold_days: 14,
          explanation_for_llm: "Inform farmer that 45kg urea was already applied 4 days ago; next split is due after 14 days.",
        },
      },
    ],
  },
  problem: {
    sectionTitle: "Quantified Problem Statement & Smallholder Vulnerability",
    headline: "Decision Blindness Across 12 Competing Farm Variables",
    summary:
      "Smallholder farmers must navigate at least 12 competing factors every single day: soil & crop stage, weather forecasts, soil moisture, electricity schedule, labour availability, machinery, seeds, fertiliser, pesticide, credit, government schemes, and mandi prices. Every advisory tool sees only one piece, and none remembers the farm history, leading to severe input waste and distress.",
    metrics: [
      {
        label: "No Technical Advisory",
        value: "57.8%",
        subtext: "Over half of Indian farm households (57.8%) received no technical advice on agriculture (only 42.2% did in 2019).",
        severity: "danger",
        trend: "NSS 77th Round, NSO (2021)",
        citationUrl: "https://mospi.gov.in/",
        tag: {
          type: "Source",
          url: "https://mospi.gov.in/",
          detail: "NSS 77th Round, NSO 2021",
        },
      },
      {
        label: "Pesticide Poisoning Deaths",
        value: "~7,000 / yr",
        subtext: "Annual accidental pesticide poisoning deaths recorded across Indian agricultural communities (2014–21 average).",
        severity: "danger",
        trend: "NCRB ADSI Data (2014–2021)",
        citationUrl: "https://ncrb.gov.in/accidental-deaths-suicides-in-india-adsi",
        tag: {
          type: "Source",
          url: "https://ncrb.gov.in/accidental-deaths-suicides-in-india-adsi",
          detail: "NCRB Accidental Deaths & Suicides in India",
        },
      },
      {
        label: "Monsoon Mission Return",
        value: "≈ 50× Return",
        subtext: "₹990 Cr invested in National Monsoon Mission & HPC generated ₹50,447 Cr in economic benefits for farmers and fishers.",
        severity: "success",
        trend: "NCAER Evaluation for MoES (2020)",
        citationUrl: "https://www.deccanherald.com/",
        tag: {
          type: "Source",
          url: "https://www.deccanherald.com/",
          detail: "NCAER Report for Ministry of Earth Sciences, 2020",
        },
      },
      {
        label: "Extreme Weather Exposure",
        value: "68.9 Million Ha",
        subtext: "33.9 million hectares lost to excess rain and 35.0 million hectares lost to drought between 2015 and 2021.",
        severity: "warning",
        trend: "World Economic Forum (via AffairsCloud, 2024)",
        citationUrl:
          "https://affairscloud.com/india-lost-33-9-million-hectares-of-crops-due-to-excess-rains-during-2015-21-wef-report/",
        tag: {
          type: "Source",
          url: "https://affairscloud.com/india-lost-33-9-million-hectares-of-crops-due-to-excess-rains-during-2015-21-wef-report/",
          detail: "WEF Report on Indian Crop Loss 2015-2021",
        },
      },
    ],
    economicLossDetails: [
      {
        category: "1. Advisory Deficit & Information Fragmentation",
        annualLoss: "57.8% of farm households without technical advice",
        rootCause:
          "According to NSS 77th Round (NSO 2021), over half of India's 140 million agricultural households receive zero technical agricultural advice. Existing extension systems have a 1:1,500 worker-to-farmer deficit.",
        impactMetrics: [
          "57.8% farm households lack access to technical advice (NSO 2021)",
          "Only 42.2% received any advice from extension or media channels",
          "Advisory is fragmented across separate, uncoordinated agencies",
        ],
        citation: {
          title: "Situation Assessment of Agricultural Households (NSS 77th Round)",
          source: "National Statistical Office (NSO) / MOSPI 2021",
          url: "https://mospi.gov.in/",
        },
      },
      {
        category: "2. Chemical Safety & Accidental Poisoning",
        annualLoss: "~7,000 accidental poisoning deaths per year",
        rootCause:
          "Without clear, vernacular spraying safety checks, farmers spray in high heat or before rainstorms, causing chemical wash-off and acute exposure risks.",
        impactMetrics: [
          "~7,000 accidental pesticide poisoning deaths/yr (2014-21 avg, NCRB)",
          "Over-application wastes expensive inputs without improving yield",
          "Dosages must be governed by strict rules, never guessed by an LLM",
        ],
        citation: {
          title: "Accidental Deaths & Suicides in India (ADSI)",
          source: "National Crime Records Bureau (NCRB)",
          url: "https://ncrb.gov.in/accidental-deaths-suicides-in-india-adsi",
        },
      },
      {
        category: "3. Extreme Weather Crop Exposure",
        annualLoss: "68.9 million hectares affected (2015–2021)",
        rootCause:
          "Farmers make irreversible decisions—such as sowing seeds, spraying chemicals, or irrigating—hours before unpredicted precipitation or heat spikes occur.",
        impactMetrics: [
          "33.9M hectares damaged by excess rain (2015–21, WEF report)",
          "35.0M hectares damaged by severe drought conditions (2015–21)",
          "Proactive, hourly micro-weather checks prevent input wash-off",
        ],
        citation: {
          title: "WEF Report on India Crop Losses Due to Weather",
          source: "World Economic Forum (AffairsCloud 2024)",
          url: "https://affairscloud.com/india-lost-33-9-million-hectares-of-crops-due-to-excess-rains-during-2015-21-wef-report/",
        },
      },
      {
        category: "4. Digital Agriculture Mission & Public Infrastructure",
        annualLoss: "₹2,817 Crore National DPI Investment",
        rootCause:
          "The Union Cabinet approved the Digital Agriculture Mission with an outlay of ₹2,817 Cr, establishing AgriStack (Farmer ID) and the Krishi Decision Support System (Krishi-DSS) to enable verified public digital services.",
        impactMetrics: [
          "₹2,817 Cr approved for Digital Agriculture Mission (PIB Sept 2024)",
          "Establishes AgriStack farmer registry and plot geo-referencing",
          "KrishiSmriti aligns directly as a citizen-facing decision layer",
        ],
        citation: {
          title: "Cabinet Approves Digital Agriculture Mission",
          source: "Press Information Bureau (PIB), Government of India, Sept 2024",
          url: "https://pib.gov.in/",
        },
      },
    ],
    gapComparison: {
      legacyTitle: "Fragmented Advisory Tools (Single-Variable Blindness)",
      legacyPoints: [
        "Unassisted integration burden: Farmer must manually check rain app, mandi board, and fertilizer bag separately",
        "Probabilistic LLM hallucinations: Chatbots generating chemical quantities or active ingredients from training text",
        "Zero farm memory: Assistant treats every question as day-zero, with no record of past sprays or urea applications",
        "Commercial marketplace bias: Input seller apps incentivized to recommend buying more chemical inputs",
        "Text and form barriers: Complex enterprise dashboards requiring high digital literacy and English reading",
      ],
      solutionTitle: "KrishiSmriti: Farm Memory + Cross-Factor Check",
      solutionPoints: [
        "One daily decisive action: Answers 'What is the single best action I should take right now?'",
        "Rule engine does the math: Chemical calculations executed in verified TypeScript code, never by the LLM",
        "Farm memory timeline: Remembers plot inputs, previous sprays, soil moisture, and crop stage in PostgreSQL/pgvector",
        "Vendor-neutral advice: No inputs sold; frequently instructs the farmer NOT to spray or buy when conditions are adverse",
        "Voice-first vernacular PWA: Marathi and Hindi voice in/out with visual cards and offline cached plan",
      ],
    },
  },
  competitiveMatrix: {
    sectionTitle: "Fair Ecosystem Benchmark",
    headline: "How KrishiSmriti Compares with Existing Agricultural Tools",
    summary:
      "A factual, objective comparison across agricultural advisory chatbots, government scheme bots, public weather apps, and input marketplaces.",
    platforms: [
      {
        name: "Farmer.chat (Digital Green)",
        category: "Extension",
        badge: "Advisory Chatbot",
        whatTheyClaim:
          "AI assistant with 1M+ users providing verified extension advice across voice, text, and images with push notifications.",
        whereTheyFail:
          "Built primarily for extension advisory and validated agronomic content; does not maintain a stateful farm memory of past fertilizer applications per plot.",
        failReason:
          "Focuses on general crop guidance rather than cross-checking plot input history (e.g. 'urea applied 4 days ago') against live hourly rain.",
        howWeOvercome:
          "Adds persistent episodic plot memory and a deterministic cross-factor rule engine to verify daily actions before speaking.",
        isOurSolution: false,
        scoreCard: {
          conflictResolution: false,
          deterministicMath: false,
          vernacularVoice: true,
          vendorNeutral: true,
          smallholderOptimized: true,
        },
      },
      {
        name: "KissanAI / Dhenu",
        category: "Chatbot",
        badge: "Generative Assistant",
        whatTheyClaim:
          "Conversational voice assistant answering agricultural queries in multiple Indian languages using LLMs.",
        whereTheyFail:
          "Relies on generative LLM synthesis for responses; without hard rule engine gates, numerical dosages may vary probabilistically.",
        failReason:
          "Generative text models do not guarantee strict adherence to State Agricultural University Package of Practices tables.",
        howWeOvercome:
          "Dosages are strictly computed by our TypeScript ICAR rule engine; the LLM is only used to format natural vernacular explanations.",
        isOurSolution: false,
        scoreCard: {
          conflictResolution: false,
          deterministicMath: false,
          vernacularVoice: true,
          vendorNeutral: true,
          smallholderOptimized: true,
        },
      },
      {
        name: "Kisan e-Mitra",
        category: "Extension",
        badge: "Public Scheme Bot",
        whatTheyClaim:
          "AI chatbot launched for PM-KISAN scheme queries in 11 languages, developed by Wadhwani AI for MoA&FW.",
        whereTheyFail:
          "Specialized for government scheme queries, installment status, and eligibility; does not provide agronomic decision support or mandi telemetry.",
        failReason:
          "Domain-specific focus on scheme administration rather than field-level agronomic and weather cross-checks.",
        howWeOvercome:
          "KrishiSmriti integrates scheme reminders into a holistic daily farm plan alongside weather, soil, and labor.",
        isOurSolution: false,
        scoreCard: {
          conflictResolution: false,
          deterministicMath: true,
          vernacularVoice: true,
          vendorNeutral: true,
          smallholderOptimized: true,
        },
      },
      {
        name: "Meghdoot / Mausam (IMD)",
        category: "Enterprise",
        badge: "Public Weather App",
        whatTheyClaim:
          "Official IMD/ICAR mobile apps providing district and block-level agromet advisories in regional languages.",
        whereTheyFail:
          "Presents tabular weather forecasts and district bulletins; does not track individual farmer field logs or resolve farm-level trade-offs.",
        failReason:
          "Broad broadcast format; cannot answer personalized questions like 'Can I spray my sugarcane in Haveli tomorrow morning?'.",
        howWeOvercome:
          "Plugs into Open-Meteo and IMD feeds, pairing them with the farmer's exact geofenced plot and input timeline.",
        isOurSolution: false,
        scoreCard: {
          conflictResolution: true,
          deterministicMath: true,
          vernacularVoice: false,
          vendorNeutral: true,
          smallholderOptimized: false,
        },
      },
      {
        name: "AgroStar / DeHaat",
        category: "E-Commerce",
        badge: "Input Marketplace",
        whatTheyClaim:
          "Full-stack platforms providing agricultural inputs, agronomic advisory, and output market linkages.",
        whereTheyFail:
          "Commercial marketplace business model: revenue is generated from selling chemical inputs, creating potential commercial bias.",
        failReason:
          "Input sellers are commercially incentivized to sell products; unlikely to advise a farmer to skip a chemical spray.",
        howWeOvercome:
          "Vendor-neutral architecture: KrishiSmriti sells no physical inputs and frequently advises farmers NOT to spray or purchase inputs.",
        isOurSolution: false,
        scoreCard: {
          conflictResolution: false,
          deterministicMath: true,
          vernacularVoice: true,
          vendorNeutral: false,
          smallholderOptimized: true,
        },
      },
      {
        name: "KrishiSmriti",
        category: "Second Brain",
        badge: "Farm Second Brain",
        whatTheyClaim:
          "Cross-factor decision engine with persistent farm memory, deterministic rule engine math, and dialect voice.",
        whereTheyFail:
          "Current prototype is focused on core decision rules (sugarcane/wheat/soybean); comprehensive IoT sensor networks and state-wide rollouts are in active development.",
        failReason: "Requires active connectivity or cached PWA state; field IoT hardware deployment requires Gram Panchayat funding.",
        howWeOvercome:
          "Combines Open-Meteo, SoilGrids, and Agmarknet into a daily single best action, backed by an auditable TypeScript rule engine.",
        isOurSolution: true,
        scoreCard: {
          conflictResolution: true,
          deterministicMath: true,
          vernacularVoice: true,
          vendorNeutral: true,
          smallholderOptimized: true,
        },
      },
    ],
  },
  architecture: {
    sectionTitle: "System Architecture & Engineering Stack",
    headline: "Next.js App Router, PostgreSQL PostGIS/pgvector & Bhashini Voice",
    summary:
      "A voice-first PWA matching the submitted SIH 2026 presentation: Open-Meteo hourly weather, SoilGrids 250m soil chemistry, and Agmarknet feeds flow into a deterministic TypeScript rule engine and PostgreSQL farm memory.",
    columns: [
      {
        layerNumber: 1,
        title: "Client & Ingestion Layer",
        subtitle: "Voice PWA & Multi-Source APIs",
        throughput: "Parallel fetch on demand",
        items: [
          {
            name: "Voice-First Progressive Web App (PWA)",
            tech: "Next.js 14 (App Router) + TypeScript + Leaflet",
            description:
              "Mobile-responsive interface operable at 380px screen width. Allows drawing 2.5-acre plot geofence on OpenStreetMap and records Marathi/Hindi voice queries.",
            specs: ["PWA offline service worker", "Leaflet polygon centroid", "Sub-200ms client hydration"],
          },
          {
            name: "Telemetry Data Fetchers",
            tech: "Open-Meteo + SoilGrids API + Agmarknet OGD",
            description:
              "Server-side route handlers fetch hourly precipitation forecasts, baseline soil NPK & pH, and nearest APMC modal price feeds in parallel.",
            specs: ["Hourly weather forecast", "250m soil chemistry", "Daily APMC mandi prices"],
          },
        ],
      },
      {
        layerNumber: 2,
        title: "Farm Memory & Rule Engine",
        subtitle: "PostgreSQL, PostGIS & TypeScript Math",
        throughput: "Deterministic execution",
        items: [
          {
            name: "Plot Memory & History Timeline",
            tech: "PostgreSQL + PostGIS + pgvector",
            description:
              "Stores plot geofence polygons, chronological logs of past sprays, urea doses, irrigation dates, and labour availability for Ramu Yadav's plot (MH-PUN-402).",
            specs: ["PostGIS plot centroid", "Episodic input logging", "pgvector similarity matching"],
          },
          {
            name: "Deterministic ICAR Rule Engine",
            tech: "TypeScript (Server-Side Node.js)",
            description:
              "Per-hectare first calculations based on official ICAR & MPKV Rahuri Package of Practices. Bars the LLM from computing chemical dosages or guessing numbers.",
            specs: ["Per-hectare first math", "Urea/DAP/MOP standard grades", "Capped at PoP maximum"],
          },
        ],
      },
      {
        layerNumber: 3,
        title: "Voice Synthesis & Output Gate",
        subtitle: "Bhashini ULCA & Number Verification",
        throughput: "Verified speech reply",
        items: [
          {
            name: "Number Check & Verification Gate",
            tech: "Regex Assertion & Fact-Checking Filter",
            description:
              "Before any spoken reply is sent, all numbers, times, and dosages are checked against the rule-engine JSON. If a mismatch is detected, it falls back to a verified template.",
            specs: ["Source number matching", "Template fallback on mismatch", "Zero fabricated quantities"],
          },
          {
            name: "Bhashini Multilingual Speech Engine",
            tech: "Bhashini ULCA ASR/TTS + Web Speech API fallback",
            description:
              "Translates queries and synthesizes natural Marathi and Hindi spoken advisories with an English translation card for evaluators.",
            specs: ["Marathi & Hindi native voice", "Web Speech API fallback", "Single decisive daily action"],
          },
        ],
      },
    ],
    parallelApis: [
      {
        name: "1. Open-Meteo Weather API",
        source: "Open-Meteo GmbH / NOAA GFS",
        purpose: "Hourly precipitation probability, 10m wind speed, temperature & humidity",
        cadence: "Real-time fetch on plot trigger",
        protocol: "HTTPS / REST JSON",
        status: "LIVE",
        sampleOutput: '{"precipitation_probability": 75, "rain_mm": 18.2, "wind_kmh": 8.5}',
      },
      {
        name: "2. SoilGrids (ISRIC) API",
        source: "ISRIC World Soil Information",
        purpose: "Baseline soil chemistry (Vertisol / Black Cotton Soil), clay %, organic carbon, pH",
        cadence: "Cached 30-day spatial tile",
        protocol: "REST API / JSON",
        status: "PARALLEL",
        sampleOutput: '{"soil_type": "Vertisol", "clay_pct": 54.2, "ph": 7.8}',
      },
      {
        name: "3. Agmarknet Mandi API",
        source: "data.gov.in Open Government Data Platform",
        purpose: "Modal auction prices for Sugarcane / Jaggery across Pune and regional APMCs",
        cadence: "Daily refresh",
        protocol: "REST API / JSON",
        status: "LIVE",
        sampleOutput: '{"market": "Pune APMC", "modal_price": 3150, "commodity": "Sugarcane"}',
      },
      {
        name: "4. Bhashini Speech API",
        source: "MeitY Digital India Bhashini Division",
        purpose: "Speech-to-text (ASR) and text-to-speech (TTS) for regional Indian languages",
        cadence: "Real-time bidirectional voice",
        protocol: "HTTPS / REST & Web Speech fallback",
        status: "LIVE",
        sampleOutput: '{"language": "mr", "status": "VOICE_SYNTHESIZED"}',
      },
    ],
  },
  personalizationLayers: [
    {
      layerNumber: 1,
      title: "Geofenced Plot Centroid & Terrain",
      subtitle: "Plot Boundary vs District Generalities",
      staticKnowledge: "Static weather model reports general Pune district rain (e.g. 20mm).",
      personalizationEngine:
        "Extracts Ramu Yadav's exact 2.5-acre plot centroid in Haveli, Pune. Verifies soil type (Black Cotton Soil) and poor drainage properties to evaluate waterlogging risks.",
      mathematicalEquation: "\\text{Plot Centroid} = \\left( \\frac{1}{n} \\sum_{i=1}^n \\text{lat}_i, \\frac{1}{n} \\sum_{i=1}^n \\text{lon}_i \\right)",
      practicalExample:
        "Identified Ramu's plot sits in heavy black Vertisol, which turns into intractable mud if 18mm rain falls, locking machinery out for 4-5 days.",
      iconType: "spatial",
    },
    {
      layerNumber: 2,
      title: "Deterministic ICAR Fertilizer Sizing",
      subtitle: "Per-Hectare First Balance vs Guesswork",
      staticKnowledge: "Generic advice says 'Apply 1 bag urea every month'.",
      personalizationEngine:
        "Checks farm memory timeline: 45 kg urea was already applied 4 days ago. Cites MPKV Rahuri sugarcane PoP to strictly defer secondary top-dressing until day 14.",
      mathematicalEquation: "\\text{Deficit} = \\max(0, \\text{Target}_{\\text{PoP}} - \\text{SHC Available}), \\quad \\text{Scaled by } \\frac{\\text{Acres}}{2.471}",
      practicalExample:
        "Prevented a duplicate 45 kg urea application, saving input costs and preventing vegetative nitrogen burns.",
      iconType: "soil",
    },
    {
      layerNumber: 3,
      title: "Mandi Price Discovery & Proximity",
      subtitle: "Spot Price Transparency vs Middlemen",
      staticKnowledge: "Local village brokers quote ₹2,800/quintal at farmgate.",
      personalizationEngine:
        "Pulls live Agmarknet modal price for Pune APMC (₹3,150/qtl). Subtracts estimated freight (₹45/qtl) to verify net farmgate advantage.",
      mathematicalEquation: "\\text{Net Revenue} = \\text{APMC Modal Price} - \\text{Freight Transport Cost}",
      practicalExample:
        "Informed Ramu of a net +₹305/quintal premium at Pune APMC yard over distress farmgate offers.",
      iconType: "profit",
    },
    {
      layerNumber: 4,
      title: "Labour & Power Timing Alignment",
      subtitle: "Pump Power Slots & Worker Availability",
      staticKnowledge: "Calendar says 'Irrigate sugarcane plot weekly'.",
      personalizationEngine:
        "Checks DISCOM feeder power schedule (6:00 AM - 10:00 AM) and current soil moisture (38%). Since moisture is sufficient and rain is expected, irrigation is postponed.",
      mathematicalEquation: "\\text{Irrigate Flag} = (\\text{Soil Moisture} < 25\\%) \\land (\\text{Rain Forecast} < 5\\text{mm}) \\land (\\text{Power Active})",
      practicalExample:
        "Skipped redundant 4-hour pump cycle during the morning power slot, saving electricity and avoiding root asphyxiation.",
      iconType: "labor",
    },
    {
      layerNumber: 5,
      title: "Vernacular Voice in Marathi & Hindi",
      subtitle: "Bhashini Speech Synthesis & Audio Cards",
      staticKnowledge: "Technical English PDF bulletins from agricultural universities.",
      personalizationEngine:
        "Converts the single best action into clear, respectful spoken Marathi and Hindi audio notes, accompanied by a visual checklist and evaluator English translation.",
      practicalExample:
        "Spoke directly in Marathi: 'राम-राम रामूजी, उद्या सकाळी ६:३० ते ९ या वेळेत फवारणी पूर्ण करा. ११ नंतर पाऊस सुरू होण्याची शक्यता आहे.'",
      iconType: "vernacular",
    },
  ],
  conflictScenarios: [
    {
      id: "SCN-01",
      title: "Ramu Yadav: Rain Tomorrow + 45kg Urea Applied 4 Days Ago + Black Soil",
      crop: "Sugarcane (Co-86032)",
      location: "Haveli, Pune, Maharashtra",
      farmerName: "Ramu Yadav (2.5 Acres, MH-PUN-402)",
      variables: {
        weatherRisk: "75% rain probability tomorrow after 11:00 AM (18.2mm expected); calm wind 6:30–9:00 AM",
        marketPrice: "Pune APMC Sugarcane/Gur modal rate steady at ₹3,150/quintal",
        soilCondition: "Black Cotton Soil (38% moisture); 45 kg urea already applied 4 days ago",
        laborStatus: "2 workers available tomorrow morning; pump power active 6:00–10:00 AM",
      },
      singleBestAction:
        "DO NOT APPLY UREA; SKIP IRRIGATION. If spraying micronutrients, spray between 6:30 AM and 9:00 AM tomorrow before rain starts at 11:00 AM.",
      actionReasoning:
        "Urea top-dressing was logged 4 days ago; applying more now violates ICAR split-dose guidelines and risks heavy rain leaching. Soil moisture is at 38%, so irrigation is unnecessary.",
      savedAmount: "Saved ₹540 in wasted urea + prevented chemical leaching",
      audioDialect: "Marathi (Bhashini TTS)",
    },
    {
      id: "SCN-02",
      title: "Soil Moisture Low (18%) + Power Slot Active Tonight + No Rain",
      crop: "Sugarcane (Co-86032)",
      location: "Haveli, Pune, Maharashtra",
      farmerName: "Ramu Yadav (2.5 Acres, MH-PUN-402)",
      variables: {
        weatherRisk: "Clear skies for 72 hours; daytime temperatures reaching 34°C",
        marketPrice: "Market steady at ₹3,150/quintal",
        soilCondition: "Soil moisture dropped to 18% (critical threshold for vegetative tillering)",
        laborStatus: "DISCOM rural three-phase power scheduled for 10:00 PM – 4:00 AM tonight",
      },
      singleBestAction:
        "IRRIGATE TONIGHT. Turn on drip/furrow irrigation during the 10:00 PM to 2:00 AM power window.",
      actionReasoning:
        "Soil moisture is at 18% and zero rain is forecast. Night-time irrigation minimizes evapotranspiration losses and utilizes the subsidized three-phase power slot.",
      savedAmount: "Protected vegetative growth and saved 25% water vs midday irrigation",
      audioDialect: "Marathi (Bhashini TTS)",
    },
  ],
  feasibility: {
    sectionTitle: "Feasibility, Risk Matrix & Verifiable Safeguards",
    headline: "Engineered Safeguards Grounded in Physical Realities",
    summary:
      "Agronomic decisions directly affect family livelihoods. We replace ungrounded generative predictions with deterministic rules, schema validation, and failover mechanisms.",
    rows: [
      {
        id: "KR-01",
        riskCategory: "Dosage Safety",
        riskTitle: "Hallucinated Chemical Dosages or Timing",
        riskDescription:
          "An LLM hallucinating chemical names or miscalculating kilograms per acre could burn crops or cause toxic runoff.",
        severity: "CRITICAL",
        safeguardTitle: "TypeScript Rule Engine Guardrail (ICAR PoP)",
        safeguardDescription:
          "The LLM is strictly barred from doing math. Dosages are calculated by our TypeScript rule engine from official ICAR & MPKV Rahuri Package of Practices tables.",
        engineeringImplementation:
          "All numbers in the reply are checked against source tool output before sending. If a mismatch is detected, the system reverts to a verified template.",
      },
      {
        id: "KR-02",
        riskCategory: "Rural Connectivity",
        riskTitle: "Intermittent 2G/4G Network Outages",
        riskDescription:
          "Smallholder farmers frequently lose internet connection when working in remote agricultural fields.",
        severity: "HIGH",
        safeguardTitle: "PWA Service Worker Offline Caching",
        safeguardDescription:
          "The PWA caches the latest daily plan and verified fertilizer tables in local IndexedDB/localStorage. A plain text SMS fallback template is prepared.",
        engineeringImplementation:
          "Service worker serves cached daily plan offline; queues voice logs for background synchronization upon reconnection.",
      },
      {
        id: "KR-03",
        riskCategory: "Data Privacy & Compliance",
        riskTitle: "Farmer Plot & Personal Data Protection",
        riskDescription:
          "Unauthorised sharing of farmer plot coordinates or economic logs could violate data protection norms.",
        severity: "HIGH",
        safeguardTitle: "Consent-Based AgriStack Alignment (DPDP Act 2023)",
        safeguardDescription:
          "Farmer plot data is indexed by anonymized UUIDs and local 7/12 survey numbers. No personal data is shared with commercial third parties.",
        engineeringImplementation:
          "Strict row-level security in PostgreSQL; consent-based authentication matching Digital Agriculture Mission guidelines.",
      },
      {
        id: "KR-04",
        riskCategory: "Hardware & Sensor Cost",
        riskTitle: "Sensor Hardware Capital Expense for Smallholders",
        riskDescription:
          "Individual smallholder farmers cannot afford expensive individual IoT soil probes or automated weather stations.",
        severity: "MEDIUM",
        safeguardTitle: "Panchayat-Level Shared Deployment & Satellite Fallback",
        safeguardDescription:
          "Sensors are deployed at the Gram Panchayat level funded via Digital Agriculture Mission grants. For farms without sensors, Open-Meteo and SoilGrids serve as baselines.",
        engineeringImplementation:
          "Hierarchical data fallback: Physical Sensor -> Open-Meteo Hourly -> SoilGrids 250m baseline.",
      },
    ],
  },
  impact: {
    sectionTitle: "Impact & Evaluation Parameters",
    headline: "Measurable Social, Economic & Environmental Benefits",
    summary:
      "Grounded in verified government reports and field economics, KrishiSmriti empowers smallholders through transparent decision guidance.",
    rows: [
      {
        dimension: "Decision Architecture",
        statusQuo: "Single-factor guessing (watching price only or weather only)",
        ourSolution: "Cross-factor check (evaluates weather, soil moisture, labour & power together)",
        metricGain: "Single best action daily",
        tag: {
          type: "Design target",
          detail: "Core prototype workflow",
        },
      },
      {
        dimension: "Dosage & Chemical Safety",
        statusQuo: "LLMs guess dosages; over half of farmers lack advice (NSO 2021)",
        ourSolution: "Rule engine computes dosages from ICAR PoP; numbers verified before sending",
        metricGain: "Zero unverified dosage calculations",
        tag: {
          type: "Measured",
          detail: "28 / 28 ICAR test assertions passed (18 Sep 2026)",
        },
      },
      {
        dimension: "Advisory Access",
        statusQuo: "57.8% of agricultural households receive no technical advice (NSO 2021)",
        ourSolution: "Voice-first PWA in Marathi and Hindi with offline caching",
        metricGain: "Zero-text vernacular access",
        tag: {
          type: "Source",
          url: "https://mospi.gov.in/",
          detail: "NSS 77th Round, NSO 2021",
        },
      },
      {
        dimension: "Mandi Price Transparency",
        statusQuo: "Reliance on village middlemen quotes without nearby APMC visibility",
        ourSolution: "Direct Agmarknet modal price lookup via data.gov.in OGD API",
        metricGain: "Transparent market data",
        tag: {
          type: "Source",
          url: "https://data.gov.in/resource/current-daily-price-various-commodities-various-markets-mandi",
          detail: "Agmarknet via data.gov.in",
        },
      },
      {
        dimension: "Commercial Objectivity",
        statusQuo: "Input marketplace apps commercially incentivized to sell more chemicals",
        ourSolution: "Vendor-neutral advisor selling no inputs; frequently advises NOT to spray",
        metricGain: "100% vendor-neutral",
        tag: {
          type: "Design target",
          detail: "Public digital infrastructure model",
        },
      },
    ],
  },
  proofOfWork: {
    sectionTitle: "Proof of Work & Verifiable Assets",
    headline: "Auditable Codebase & Interactive Working Prototype",
    summary:
      "All code, rule engines, unit tests, and API schemas are open for evaluator inspection.",
    items: [
      {
        id: "repo",
        title: "GitHub Repository (Public & Auditable)",
        subtitle: "Next.js App Router, Rule Engine & Test Suites",
        badge: "Public SIH 2026 Repo",
        description:
          "Complete source code including ICAR fertilizer calculator, unit tests, and responsive PWA interface.",
        actionText: "Open GitHub Repository",
        url: "https://github.com/lohitakshcodes/claudemaxdedo-sih2026",
      },
      {
        id: "api",
        title: "Interactive API Schema Inspector",
        subtitle: "Next.js Route Handlers & Zod Schemas",
        badge: "Zod & OpenAPI",
        description:
          "Inspect API schemas for `/api/krishismriti` and test live deterministic cross-factor validation.",
        actionText: "Inspect API Schemas",
        modalType: "swagger",
      },
      {
        id: "dataset",
        title: "Soil & Crop Benchmark Datasets",
        subtitle: "ICAR Package of Practices & Soil Health Values",
        badge: "Verified Datasets",
        description:
          "Review MPKV Rahuri sugarcane nutrient recommendations, Vertisol soil profiles, and Agmarknet price samples.",
        actionText: "View Datasets",
        modalType: "dataset",
      },
      {
        id: "audio",
        title: "Vernacular Audio Voice Notes",
        subtitle: "Bhashini Speech Pipeline Samples",
        badge: "Marathi & Hindi Audio",
        description:
          "Listen to sample vernacular voice advisories synthesized for Ramu Yadav in Marathi and Hindi.",
        actionText: "Play Voice Samples",
        modalType: "audio",
      },
    ],
  },
  team: {
    sectionTitle: "Team Execution Roster",
    headline: "Team ClaudeMaxDedo (Team ID SIH079)",
    summary:
      "Student engineering team building practical digital solutions for Smart India Hackathon 2026.",
    members: [
      {
        name: "Shreya Deshpande",
        operationalRole: "Team Leader & Rule Engine Architect",
        coreDiscipline: "Applied AI & Agronomic Logic",
        keyContributions: [
          "Designed ICAR Package of Practices deterministic rule engine",
          "Structured cross-factor decision matrix and prompt templates",
        ],
        github: "https://github.com/shreyadeshpande0656",
        linkedin: "https://www.linkedin.com/in/shreya-deshpande-148945321",
        initials: "SD",
      },
      {
        name: "Lohitaksh Bisen",
        operationalRole: "Fullstack & Backend Engineer",
        coreDiscipline: "Distributed Systems & Telemetry",
        keyContributions: [
          "Built data fetchers for Open-Meteo, SoilGrids, and Agmarknet APIs",
          "Engineered Next.js App Router endpoints and number check filters",
        ],
        github: "https://github.com/lohitakshcodes",
        linkedin: "https://www.linkedin.com/in/lohitakshbisen",
        initials: "LB",
      },
      {
        name: "Tanvi Hardas",
        operationalRole: "Geospatial & Remote Sensing Specialist",
        coreDiscipline: "GIS & Spatial Analysis",
        keyContributions: [
          "Integrated Leaflet geofencing and plot centroid calculations",
          "Mapped SoilGrids 250m soil chemistry layers to plot polygons",
        ],
        github: "https://github.com/tanvihardas",
        linkedin: "https://www.linkedin.com/in/tanvihardas/",
        initials: "TH",
      },
      {
        name: "Anuj Bhure",
        operationalRole: "Frontend & PWA Lead",
        coreDiscipline: "Modern Web & Mobile UI",
        keyContributions: [
          "Architected responsive Next.js PWA tested down to 380px screens",
          "Created interactive decision sandbox, timeline, and visual soil cards",
        ],
        github: "https://github.com/anujdbhure",
        linkedin: "https://www.linkedin.com/in/anuj-d-bhure-05b22a373/",
        initials: "AB",
      },
      {
        name: "Arush Sinha",
        operationalRole: "Speech & Multilingual NLP Engineer",
        coreDiscipline: "Indic Language Processing",
        keyContributions: [
          "Integrated Bhashini ULCA ASR/TTS endpoints with browser fallback",
          "Structured Marathi and Hindi phonetic audio synthesis pipelines",
        ],
        github: "https://github.com/arushsinha896-cmd",
        linkedin: "https://www.linkedin.com/in/arushsinha206/",
        initials: "AS",
      },
      {
        name: "Siddharth Gupta",
        operationalRole: "DevOps & Database Lead",
        coreDiscipline: "Cloud Deployment & Database Architecture",
        keyContributions: [
          "Configured PostgreSQL database schemas and PostGIS spatial extensions",
          "Managed Vercel continuous deployment and automated testing pipeline",
        ],
        github: "https://github.com/SiddharthGupta2611",
        linkedin: "https://www.linkedin.com/in/siddharth-gupta-72071232b",
        initials: "SG",
      },
    ],
  },
};
